### PR TITLE
place holder support

### PR DESCRIPTION
**Pull request by sockstack**
${value} like value place holder support.

eg:
```mysql
select 
    sum(quota_value) value,
    busi_col2 as sh,
    ${a} as a,
    year(now()) as year
from 
    quota_summary
where 
    table_ename = 'gshmyyszje'
    and cd = (select id from t1 where a = ${t1})
```

### CODE REVIEW

**Comment by dbetter-endor** [comment]
I would also love to see this gets pushed in.

**Comment by albin3** [comment]
#15 #47

**Comment by ahmedragab96** [comment]
Was this change part of the latest version ? I don't think it's working

**Comment by albin3** [comment]
@ahmedragab96 not yet

**Pull request merged**
